### ISSUE TITLE
ESP32 S3

### ISSUE THREAD

**Issue by yo2ldk** [tjlab-jf3hzb/Digital_VFO_with_analog_dial_V2#1]
Excellent and Thank you for the new version !
  not an issue but a kindle request:
   can you adapt please the code instructions, for ESP32S3 version processor?
    My best regards and 73 !

**Comment by tjlab-jf3hzb** [comment]
I haven't confirmed it yet, but it seems that the same code can be used for ESP32-S3.

**Comment by yo2ldk** [comment]
unfortunately not..

![err](https://github.com/tjlab-jf3hzb/Digital_VFO_with_analog_dial_V2/assets/1875591/55ea711e-03e6-4bf7-a9f6-f431d7e21318)

**Comment by yo2ldk** [comment]
ok, in the first try not working, but who have ESP32S3 like me, need to modify the ILIxxx or STxxx.hpp file line, from
cfg.spi_host = VSPI_HOST;
to
cfg.spi_host = SPI3_HOST;

  Many Thank's !

**Comment by yo2ldk** [comment]
ok, in the first try not working, but who have ESP32S3 like me, need to modify the ILIxxx or STxxx.hpp file line, from
cfg.spi_host = VSPI_HOST;
to
cfg.spi_host = SPI3_HOST;

Many Thank's !
